---
title: "Crypto Report"
author: "Matt Majestic"
output:
  html_document:
    df_print: paged
    toc: yes
  pdf_document:
    fig_caption: yes
    fig_height: 3.5
    fig_width: 4
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}
library(coinmarketcapr)
library(ggplot2)
library(plotly)
library(dplyr)
library(DT)
library(lubridate)
source("api_key/api_coinmarket.R")
coinmarketcapr::setup(api_key = api_sourced_key)
#coinmarketcapr::get_api_info()
```
\newpage
# Introduction

Goal: Look at Crypto Trends & Identify Patterns in Data

# Methods

Data Sources

* Coin Market Cap Web API


# Results 

* Extremely volatile

```{r build,echo = FALSE,warning=FALSE}
all_coins <- get_crypto_listings() %>% mutate(year = year(date_added))
annual_mean_usd_data <- all_coins %>% dplyr::group_by(year) %>% summarise(mean_usd = mean(USD_price)) %>% as.data.frame()
annual_mean_usd_dt <-datatable(all_coins %>% dplyr::group_by(year) %>% summarise(mean_usd = mean(USD_price)),rownames = FALSE)
annual_mean_usd_dt
```

```{r visual,echo=FALSE}
plot_ly(annual_mean_usd_data,
        x=~year,
        y=~mean_usd, 
        type = 'scatter', 
        mode = 'lines')
```

# Conclusion

* *On the rise the past 2 years based on mean USD_price*

